# Generated by Django 5.0.3 on 2026-02-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("staff", "Staff"), ("user", "User")],
                default="user",
                max_length=16,
            ),
        ),
    ]
