from __future__ import annotations

import re
from collections import Counter
from io import BytesIO

from docx import Document
from pptx import Presentation as PptxPresentation


def generate_presentation_from_text(text: str):
    sentences = [s.strip() for s in text.split(".") if s.strip()]
    slides = []
    for sentence in sentences:
        slides.append({"title": sentence[:50], "content": sentence})
    return slides


def _extract_keywords(text: str, limit: int = 6) -> list[str]:
    words = re.findall(r"[a-zA-Z]{4,}", text.lower())
    stop_words = {
        "this",
        "that",
        "with",
        "from",
        "have",
        "into",
        "your",
        "their",
        "about",
        "there",
        "which",
        "were",
        "been",
        "will",
        "would",
        "could",
        "should",
    }
    counts = Counter(word for word in words if word not in stop_words)
    return [word for word, _ in counts.most_common(limit)]


def parse_word_document(uploaded_file) -> tuple[list[dict], str]:
    document = Document(uploaded_file)
    sections = []
    current_heading = "Overview"
    bucket = []

    for paragraph in document.paragraphs:
        text = paragraph.text.strip()
        if not text:
            continue
        style_name = (paragraph.style.name or "").lower() if paragraph.style else ""
        is_heading = style_name.startswith("heading")
        if is_heading and bucket:
            sections.append({"heading": current_heading, "points": bucket[:6]})
            bucket = []
        if is_heading:
            current_heading = text
        else:
            bucket.append(text)

    if bucket:
        sections.append({"heading": current_heading, "points": bucket[:6]})

    if not sections:
        flat_text = [p.text.strip() for p in document.paragraphs if p.text.strip()]
        sections = [{"heading": "Overview", "points": flat_text[:8]}]

    full_text = " ".join(point for section in sections for point in section["points"])
    keywords = _extract_keywords(full_text)

    slides = [{"title": "Document Summary", "bullets": keywords or ["No significant keywords detected."]}]
    for section in sections[:8]:
        slides.append({"title": section["heading"][:80], "bullets": section["points"][:6]})
    return slides, full_text


def build_powerpoint_file(title: str, slides: list[dict]) -> bytes:
    presentation = PptxPresentation()
    title_layout = presentation.slide_layouts[0]
    content_layout = presentation.slide_layouts[1]

    first_slide = presentation.slides.add_slide(title_layout)
    first_slide.shapes.title.text = title
    first_slide.placeholders[1].text = "Generated by OFFICE-COPILOT Document Analyst"

    for slide_data in slides:
        slide = presentation.slides.add_slide(content_layout)
        slide.shapes.title.text = slide_data["title"]
        text_frame = slide.placeholders[1].text_frame
        text_frame.clear()
        bullets = slide_data.get("bullets", [])
        if not bullets:
            bullets = ["No highlights available"]
        for idx, bullet in enumerate(bullets):
            paragraph = text_frame.paragraphs[0] if idx == 0 else text_frame.add_paragraph()
            paragraph.text = str(bullet)
            paragraph.level = 0

    output = BytesIO()
    presentation.save(output)
    output.seek(0)
    return output.getvalue()
